# Generated by Django 6.0.5 on 2026-07-15 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('designation', models.CharField(default='Advocate', max_length=150)),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=100)),
                ('practice_areas', models.CharField(help_text='Comma-separated practice areas.', max_length=255)),
                ('languages', models.CharField(max_length=255)),
                ('bar_council_registration', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='advocate_photos/')),
                ('bio', models.TextField(blank=True, help_text='Detailed biography of the advocate.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=150)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which FAQs are displayed.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(help_text='Short teaser for homepage cards.')),
                ('description', models.TextField(help_text='Detailed description for the practice area detail page.')),
                ('icon_class', models.CharField(default='fa-gavel', help_text="FontAwesome class e.g., 'fa-gavel'", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('case_or_designation', models.CharField(blank=True, help_text="e.g., 'Civil Client' or 'Business Owner'", max_length=255, null=True)),
                ('review', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating out of 5 stars.')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('client_type', models.CharField(help_text="e.g., 'Individual', 'Startup', 'Corporation'", max_length=150)),
                ('description', models.TextField()),
                ('outcome', models.TextField()),
                ('practice_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='core.practicearea')),
            ],
        ),
    ]
