# Generated by Django 6.0.5 on 2026-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('sc_judgments', 'Recent Supreme Court Judgments'), ('criminal_laws', 'New Criminal Laws'), ('property_laws', 'Property Law Updates'), ('gst_updates', 'GST Updates'), ('legal_awareness', 'Legal Awareness'), ('constitutional_law', 'Constitutional Law'), ('consumer_rights', 'Consumer Rights'), ('cyber_crime', 'Cyber Crime'), ('others', 'General Legal Updates')], default='others', max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('author', models.CharField(default='Adv. Rupesh Kumar Chaudhary', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
