# Generated by Django 6.0.5 on 2026-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('is_attended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('case_type', models.CharField(choices=[('civil', 'Civil - सिविल'), ('criminal', 'Criminal - क्रिमिनल'), ('matrimonial', 'Matrimonial - वैवाहिक मामले'), ('property', 'Property - संपत्ति मामले'), ('cheque_bounce', 'Cheque Bounce - चेक बाउंस'), ('other', 'Other - अन्य')], max_length=50)),
                ('message', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='inquiry_documents/')),
                ('is_attended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
